apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
spec:
  template:
    spec:
      tolerations:
        - key: cwmc-role
          value: operator
          effect: NoSchedule
        - key: cwmc-role
          value: monitoring
          effect: NoSchedule
