apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nirajk1/multi-tier-backend:latest
        ports:
        - containerPort: 3000
        envFrom:
         - configMapRef:
             name: app-config

