---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-project-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-project
  template:
    metadata:
      labels:
        app: todo-project
    spec:
      volumes:
        - name: next-cache
          emptyDir: {}
        - name: data-volume
          persistentVolumeClaim:
            claimName: todo-project-data-pvc
      containers:
        - name: frontend
          image: 3nd3r1/todo-project-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
          volumeMounts:
            - name: next-cache
              mountPath: /usr/src/app/.next/cache
        - name: backend
          image: 3nd3r1/todo-project-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: todo-project-database-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-project-database-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: todo-project-database-svc
            - name: POSTGRES_PORT
              value: "5432"
        - name: imagenator
          image: 3nd3r1/todo-project-imagenator:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
          volumeMounts:
            - name: data-volume
              mountPath: /usr/src/app/data
