apiVersion: apps/v1
kind: Deployment
metadata:
  name: l2fwd
  labels:
    app: l2fwd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: l2fwd
  template:
    metadata:
      labels:
        app: l2fwd
    spec:
      containers:
      - name: l2fwd
        image: shivank1128/l2l3fwd
        command: [ "/bin/bash", "-c", "--" ]
        args: ["ls -al"]
