apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: my-stats-script
  name: my-stats-script
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: my-stats-script
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: my-stats-script
    spec:
      containers:
        - args:
            - sh
            - -c
            - python stats-app.py
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka_bootstrap_servers_value
            - name: KAFKA_TOPIC
              value: kafka_topic_value
            - name: MONGO_ICMP_URI
              value: mongo_icmp_uri_value
            - name: MONGO_TCP_URI
              value: mongo_tcp_uri_value
            - name: MONGO_UDP_URI
              value: mongo_udp_uri_value
            - name: MONGO_UNKNOWN_URI
              value: mongo_unknown_uri_value
          image: ayoubtest1/statsapp:latest
          name: my-stats-script
          resources: {}
      restartPolicy: Always
status: {}
