apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: twitter-stream
  labels:
    name: twitter-stream
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: twitter-stream
    spec:
      containers:
      - name: twitter-to-pubsub
        image: gcr.io/neu-ncaa/tweetcapture-image:latest
        env:
        - name: PROCESSINGSCRIPT
          value: twitter-to-pubsub
        # Change this to your pubsub topic
        - name: PUBSUB_TOPIC
          value: projects/neu-ncaa/topics/ncaa_tweets
        # Change the following four settings to your twitter credentials
        # information.
        - name: CONSUMERKEY
          value: tfRTh5jnUVCA0200QhOmw
        - name: CONSUMERSECRET
          value: TugpxHnDtrbxFOd7P2tYYLtvEgQcbxBOBSkzwepI
        - name: ACCESSTOKEN
          value: 1671794539-bLPXnXpvCe15NrkcDPd18eKVxP86sMaoAnb2aqM
        - name: ACCESSTOKENSEC
          value: uepGhkxCn7MND4C1Fw5T9ZiZUAv74LW7X2G7Lqsm7fU
        - name: TWSTREAMMODE
          value: ncaa_tweets
        # set value to sample for tweet samples
