apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deployment
  labels:
    name: voting-deployment
    app: demo-voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: voting-app
      labels: demo-voting-app
  template:
    metadata:
      name: voting-app
      labels:
        name: voting-app
        labels: demo-voting-app
    spec:
      containers:
        - name: voting-app
          image: kodekloud/examplevotingapp_vote:v1 