apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: weathercollector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: weathercollector
        env: prod
        role: web
    spec:
      containers:
      - name: weathercollector
        image: weathercollector:v1
        ports:
        - containerPort: 8000