apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dev-api-redis
  namespace: dev-api
  labels:
    name: dev-api-redis
spec:
  template:
    metadata:
      name: dev-api-redis
      labels:   
        name: dev-api-redis
    spec:
      containers:
      - name: redis
        image: sameersbn/redis
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_PASSWORD
          value: redis@ys
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - mountPath: /var/lib/redis
          subPath: dev-api-redis
          name: redisdata
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec: 
            command:  
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: redisdata
        persistentVolumeClaim:
          claimName: dev-api-redis-pvc
