apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: oracle-proxy
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: oracle-nginx
          image: nginx:1.15.2-alpine
          imagePullPolicy: Always
          ports:
            - name: oracle-http
              containerPort: 80
            - name: oracle-https
              containerPort: 443
          volumeMounts:
            - name: oracle-nginx
              mountPath: /etc/nginx/
              readOnly: true
      volumes:
        - name: oracle-nginx
          configMap:
            name: oracle-nginx

