apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: target
  template:
    metadata:
      labels:
        app: target
    spec:
      containers:
      - name: demo
        image: centos:7
        command: ["ping", "8.8.8.8"]
